version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tpfoyer-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # Non-empty password
      MYSQL_DATABASE: tpfoyerdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  app:
    image: radwanessefi/tp-foyer:1.0.162
    container_name: tpfoyer-app
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tpfoyerdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
